name: dbt_lineage
version: "1.0.0"

profile: warehouse

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_lineage:
    staging:
      +schema: staging
      +materialized: table
    mart:
      +schema: mart
      +materialized: table
