name: 'data_pipeline'
version: '1.0.0'
config-version: 2

profile: 'data_pipeline'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_pipeline:
    dw:
      +materialized: table
      +schema: dw
